# Generated by Django 4.2.4 on 2024-03-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websitescraper_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='stringname',
            new_name='stringname1',
        ),
    ]
